--- #YAML:1.0
name:                Gnome2-Rsvg
version:             0.10
abstract:            Perl interface to the RSVG library
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Cairo:                         1.00
    ExtUtils::Depends:             0.20
    ExtUtils::PkgConfig:           1.03
    Glib:                          1.02
    Gtk2:                          1.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
